# Generated by Django 3.2.5 on 2021-12-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20211214_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerhandle',
            old_name='handle',
            new_name='name',
        ),
    ]
